INSERT INTO `ingredients` (`name`, `category`)
VALUES
('Apples', 'FRUIT'),
('Carrots', 'VEGETABLES'),
('Red Wine', 'ALCOHOL'),
('Cheddar Cheese', 'DAIRY'),
('Spaghetti', 'PASTA'),
('Basmati Rice', 'RICE'),
('Ramen Noodles', 'NOODLES'),
('Almonds', 'NUTS'),
('Olive Oil', 'FOOD_CUPBOARD'),
('All-Purpose Flour', 'BAKING'),
('Frozen Peas', 'FROZEN'),
('Ketchup', 'CONDIMENTS'),
('Whole Wheat Bread', 'BREAD'),
('Chocolate Bar', 'SWEETS'),
('Chicken Breast', 'MEAT'),
('Salmon', 'FISH'),
('Salt', 'SEASONING'),
('Bananas', 'FRUIT'),
('Broccoli', 'VEGETABLES'),
('Beer', 'ALCOHOL'),
('Butter', 'DAIRY'),
('Penne Pasta', 'PASTA'),
('Brown Rice', 'RICE'),
('Udon Noodles', 'NOODLES'),
('Cashews', 'NUTS'),
('Canned Beans', 'FOOD_CUPBOARD'),
('Sugar', 'BAKING'),
('Frozen Pizza', 'FROZEN'),
('Mustard', 'CONDIMENTS'),
('Baguette', 'BREAD'),
('Candy', 'SWEETS'),
('Ground Beef', 'MEAT'),
('Tuna', 'FISH'),
('Black Pepper', 'SEASONING'),
('Grapes', 'FRUIT'),
('Spinach', 'VEGETABLES'),
('Vodka', 'ALCOHOL'),
('Yogurt', 'DAIRY'),
('Lasagna Sheets', 'PASTA'),
('Jasmine Rice', 'RICE'),
('Soba Noodles', 'NOODLES'),
('Pistachios', 'NUTS'),
('Tomato Sauce', 'FOOD_CUPBOARD'),
('Baking Soda', 'BAKING'),
('Frozen Chicken', 'FROZEN'),
('Mayonnaise', 'CONDIMENTS'),
('Sourdough Bread', 'BREAD'),
('Lollipops', 'SWEETS'),
('Pork Chops', 'MEAT'),
('Shrimp', 'FISH'),
('Garlic Powder', 'SEASONING');
